// Code generated by ogen, DO NOT EDIT.
package api

type AnswerCallRes interface {
	answerCallRes()
}

type AudioPublicAudioTranscriptionsPostRes interface {
	audioPublicAudioTranscriptionsPostRes()
}

type BridgeCallRes interface {
	bridgeCallRes()
}

type BulkCredentialActionRes interface {
	bulkCredentialActionRes()
}

type CreateBulkTelephonyCredentialsRes interface {
	createBulkTelephonyCredentialsRes()
}

type CreateCallControlApplicationRes interface {
	createCallControlApplicationRes()
}

type CreateFlashcallVerificationRes interface {
	createFlashcallVerificationRes()
}

type CreateProfileRes interface {
	createProfileRes()
}

type CreateProfileVerificationRequestRes interface {
	createProfileVerificationRequestRes()
}

type CreateTelephonyCredentialRes interface {
	createTelephonyCredentialRes()
}

type CreateTelephonyCredentialTokenRes interface {
	createTelephonyCredentialTokenRes()
}

type CreateTexmlApplicationRes interface {
	createTexmlApplicationRes()
}

type CreateTexmlSecretRes interface {
	createTexmlSecretRes()
}

type CreateVerificationCallRes interface {
	createVerificationCallRes()
}

type CreateVerificationSmsRes interface {
	createVerificationSmsRes()
}

type CreateVerifiedNumberRes interface {
	createVerifiedNumberRes()
}

type CreateVerifyProfileRes interface {
	createVerifyProfileRes()
}

type DeleteCallControlApplicationRes interface {
	deleteCallControlApplicationRes()
}

type DeleteProfileRes interface {
	deleteProfileRes()
}

type DeleteTeXMLCallRecordingRes interface {
	deleteTeXMLCallRecordingRes()
}

type DeleteTeXMLRecordingTranscriptionRes interface {
	deleteTeXMLRecordingTranscriptionRes()
}

type DeleteTelephonyCredentialRes interface {
	deleteTelephonyCredentialRes()
}

type DeleteTelephonyCredentialsRes interface {
	deleteTelephonyCredentialsRes()
}

type DeleteTexmlApplicationRes interface {
	deleteTexmlApplicationRes()
}

type DeleteTexmlConferenceParticipantRes interface {
	deleteTexmlConferenceParticipantRes()
}

type DeleteVerifiedCallDisplayProfileRes interface {
	deleteVerifiedCallDisplayProfileRes()
}

type DeleteVerifiedNumberRes interface {
	deleteVerifiedNumberRes()
}

type DialCallRes interface {
	dialCallRes()
}

type DialTexmlConferenceParticipantRes interface {
	dialTexmlConferenceParticipantRes()
}

type DisplayProfileRes interface {
	displayProfileRes()
}

type EnqueueCallRes interface {
	enqueueCallRes()
}

type FetchTeXMLCallRecordingsRes interface {
	fetchTeXMLCallRecordingsRes()
}

type FetchTeXMLConferenceRecordingsRes interface {
	fetchTeXMLConferenceRecordingsRes()
}

type FindTelephonyCredentialsRes interface {
	findTelephonyCredentialsRes()
}

type FindTexmlApplicationsRes interface {
	findTexmlApplicationsRes()
}

type GatherCallRes interface {
	gatherCallRes()
}

type GatherUsingAudioRes interface {
	gatherUsingAudioRes()
}

type GatherUsingSpeakRes interface {
	gatherUsingSpeakRes()
}

type GetTeXMLCallRecordingRes interface {
	getTeXMLCallRecordingRes()
}

type GetTeXMLCallRecordingsRes interface {
	getTeXMLCallRecordingsRes()
}

type GetTeXMLRecordingTranscriptionRes interface {
	getTeXMLRecordingTranscriptionRes()
}

type GetTeXMLRecordingTranscriptionsRes interface {
	getTeXMLRecordingTranscriptionsRes()
}

type GetTelephonyCredentialRes interface {
	getTelephonyCredentialRes()
}

type GetTexmlApplicationRes interface {
	getTexmlApplicationRes()
}

type GetTexmlCallRes interface {
	getTexmlCallRes()
}

type GetTexmlCallsRes interface {
	getTexmlCallsRes()
}

type GetTexmlConferenceParticipantRes interface {
	getTexmlConferenceParticipantRes()
}

type GetTexmlConferenceParticipantsRes interface {
	getTexmlConferenceParticipantsRes()
}

type GetTexmlConferenceRecordingsRes interface {
	getTexmlConferenceRecordingsRes()
}

type GetTexmlConferenceRes interface {
	getTexmlConferenceRes()
}

type GetTexmlConferencesRes interface {
	getTexmlConferencesRes()
}

type GetUsageReportByApplicationRes interface {
	getUsageReportByApplicationRes()
}

type GetUserBalanceRes interface {
	getUserBalanceRes()
}

type GetVerifiedNumberRes interface {
	getVerifiedNumberRes()
}

type GetVerifyProfileRes interface {
	getVerifyProfileRes()
}

type GetWebhookDeliveryRes interface {
	getWebhookDeliveryRes()
}

type HangupCallRes interface {
	hangupCallRes()
}

type LeaveQueueRes interface {
	leaveQueueRes()
}

type ListCallControlApplicationsRes interface {
	listCallControlApplicationsRes()
}

type ListConnectionActiveCallsRes interface {
	listConnectionActiveCallsRes()
}

type ListProfilesRes interface {
	listProfilesRes()
}

type ListQueueCallsRes interface {
	listQueueCallsRes()
}

type ListTagsRes interface {
	listTagsRes()
}

type ListUsageReportsOptionsRes interface {
	listUsageReportsOptionsRes()
}

type ListVerificationsRes interface {
	listVerificationsRes()
}

type ListVerifiedCallDisplayProfilesRes interface {
	listVerifiedCallDisplayProfilesRes()
}

type ListVerifiedNumbersRes interface {
	listVerifiedNumbersRes()
}

type NoiseSuppressionStartRes interface {
	noiseSuppressionStartRes()
}

type NoiseSuppressionStopRes interface {
	noiseSuppressionStopRes()
}

type PauseCallRecordingRes interface {
	pauseCallRecordingRes()
}

type PerformCredentialActionRes interface {
	performCredentialActionRes()
}

type ReferCallRes interface {
	referCallRes()
}

type RegisterCallRes interface {
	registerCallRes()
}

type RejectCallRes interface {
	rejectCallRes()
}

type ResumeCallRecordingRes interface {
	resumeCallRecordingRes()
}

type RetrieveCallControlApplicationRes interface {
	retrieveCallControlApplicationRes()
}

type RetrieveCallFromQueueRes interface {
	retrieveCallFromQueueRes()
}

type RetrieveCallStatusRes interface {
	retrieveCallStatusRes()
}

type RetrieveVerificationRes interface {
	retrieveVerificationRes()
}

type SendDTMFRes interface {
	sendDTMFRes()
}

type SpeakCallRes interface {
	speakCallRes()
}

type StartCallForkRes interface {
	startCallForkRes()
}

type StartCallPlaybackRes interface {
	startCallPlaybackRes()
}

type StartCallRecordRes interface {
	startCallRecordRes()
}

type StartCallStreamingRes interface {
	startCallStreamingRes()
}

type StartCallTranscriptionRes interface {
	startCallTranscriptionRes()
}

type StartTeXMLCallRecordingRes interface {
	startTeXMLCallRecordingRes()
}

type StopCallForkRes interface {
	stopCallForkRes()
}

type StopCallGatherRes interface {
	stopCallGatherRes()
}

type StopCallPlaybackRes interface {
	stopCallPlaybackRes()
}

type StopCallRecordingRes interface {
	stopCallRecordingRes()
}

type StopCallStreamingRes interface {
	stopCallStreamingRes()
}

type StopCallTranscriptionRes interface {
	stopCallTranscriptionRes()
}

type TransferCallRes interface {
	transferCallRes()
}

type UpdateBulkTelephonyCredentialRes interface {
	updateBulkTelephonyCredentialRes()
}

type UpdateCallControlApplicationRes interface {
	updateCallControlApplicationRes()
}

type UpdateClientStateRes interface {
	updateClientStateRes()
}

type UpdateProfileRes interface {
	updateProfileRes()
}

type UpdateTeXMLCallRecordingRes interface {
	updateTeXMLCallRecordingRes()
}

type UpdateTelephonyCredentialRes interface {
	updateTelephonyCredentialRes()
}

type UpdateTexmlApplicationRes interface {
	updateTexmlApplicationRes()
}

type UpdateTexmlConferenceParticipantRes interface {
	updateTexmlConferenceParticipantRes()
}

type UpdateTexmlConferenceRes interface {
	updateTexmlConferenceRes()
}

type UpdateVerifyProfileRes interface {
	updateVerifyProfileRes()
}

type VerifyVerificationCodeByPhoneNumberRes interface {
	verifyVerificationCodeByPhoneNumberRes()
}

type VerifyVerificationCodeRes interface {
	verifyVerificationCodeRes()
}
