// Code generated by ogen, DO NOT EDIT.
package api

type AnswerCallRes interface {
	answerCallRes()
}

type BridgeCallRes interface {
	bridgeCallRes()
}

type CreateFlashcallVerificationRes interface {
	createFlashcallVerificationRes()
}

type CreateTexmlApplicationRes interface {
	createTexmlApplicationRes()
}

type CreateTexmlSecretRes interface {
	createTexmlSecretRes()
}

type CreateVerificationCallRes interface {
	createVerificationCallRes()
}

type CreateVerificationSmsRes interface {
	createVerificationSmsRes()
}

type CreateVerifiedNumberRes interface {
	createVerifiedNumberRes()
}

type DeleteProfileRes interface {
	deleteProfileRes()
}

type DeleteTeXMLCallRecordingRes interface {
	deleteTeXMLCallRecordingRes()
}

type DeleteTeXMLRecordingTranscriptionRes interface {
	deleteTeXMLRecordingTranscriptionRes()
}

type DeleteTexmlApplicationRes interface {
	deleteTexmlApplicationRes()
}

type DeleteTexmlConferenceParticipantRes interface {
	deleteTexmlConferenceParticipantRes()
}

type DeleteVerifiedNumberRes interface {
	deleteVerifiedNumberRes()
}

type DialCallRes interface {
	dialCallRes()
}

type DialTexmlConferenceParticipantRes interface {
	dialTexmlConferenceParticipantRes()
}

type EnqueueCallRes interface {
	enqueueCallRes()
}

type FetchTeXMLCallRecordingsRes interface {
	fetchTeXMLCallRecordingsRes()
}

type FetchTeXMLConferenceRecordingsRes interface {
	fetchTeXMLConferenceRecordingsRes()
}

type FindTexmlApplicationsRes interface {
	findTexmlApplicationsRes()
}

type GatherCallRes interface {
	gatherCallRes()
}

type GatherUsingAudioRes interface {
	gatherUsingAudioRes()
}

type GatherUsingSpeakRes interface {
	gatherUsingSpeakRes()
}

type GetTeXMLCallRecordingRes interface {
	getTeXMLCallRecordingRes()
}

type GetTeXMLCallRecordingsRes interface {
	getTeXMLCallRecordingsRes()
}

type GetTeXMLRecordingTranscriptionRes interface {
	getTeXMLRecordingTranscriptionRes()
}

type GetTeXMLRecordingTranscriptionsRes interface {
	getTeXMLRecordingTranscriptionsRes()
}

type GetTexmlApplicationRes interface {
	getTexmlApplicationRes()
}

type GetTexmlCallRes interface {
	getTexmlCallRes()
}

type GetTexmlCallsRes interface {
	getTexmlCallsRes()
}

type GetTexmlConferenceParticipantRes interface {
	getTexmlConferenceParticipantRes()
}

type GetTexmlConferenceParticipantsRes interface {
	getTexmlConferenceParticipantsRes()
}

type GetTexmlConferenceRecordingsRes interface {
	getTexmlConferenceRecordingsRes()
}

type GetTexmlConferenceRes interface {
	getTexmlConferenceRes()
}

type GetTexmlConferencesRes interface {
	getTexmlConferencesRes()
}

type GetUsageReportByApplicationRes interface {
	getUsageReportByApplicationRes()
}

type GetVerifiedNumberRes interface {
	getVerifiedNumberRes()
}

type GetVerifyProfileRes interface {
	getVerifyProfileRes()
}

type HangupCallRes interface {
	hangupCallRes()
}

type LeaveQueueRes interface {
	leaveQueueRes()
}

type ListQueueCallsRes interface {
	listQueueCallsRes()
}

type ListUsageReportsOptionsRes interface {
	listUsageReportsOptionsRes()
}

type ListVerificationsRes interface {
	listVerificationsRes()
}

type ListVerifiedNumbersRes interface {
	listVerifiedNumbersRes()
}

type NoiseSuppressionStartRes interface {
	noiseSuppressionStartRes()
}

type NoiseSuppressionStopRes interface {
	noiseSuppressionStopRes()
}

type PauseCallRecordingRes interface {
	pauseCallRecordingRes()
}

type ReferCallRes interface {
	referCallRes()
}

type RegisterCallRes interface {
	registerCallRes()
}

type RejectCallRes interface {
	rejectCallRes()
}

type ResumeCallRecordingRes interface {
	resumeCallRecordingRes()
}

type RetrieveCallFromQueueRes interface {
	retrieveCallFromQueueRes()
}

type RetrieveCallStatusRes interface {
	retrieveCallStatusRes()
}

type RetrieveVerificationRes interface {
	retrieveVerificationRes()
}

type SendDTMFRes interface {
	sendDTMFRes()
}

type SpeakCallRes interface {
	speakCallRes()
}

type StartCallForkRes interface {
	startCallForkRes()
}

type StartCallPlaybackRes interface {
	startCallPlaybackRes()
}

type StartCallRecordRes interface {
	startCallRecordRes()
}

type StartCallStreamingRes interface {
	startCallStreamingRes()
}

type StartCallTranscriptionRes interface {
	startCallTranscriptionRes()
}

type StartTeXMLCallRecordingRes interface {
	startTeXMLCallRecordingRes()
}

type StopCallForkRes interface {
	stopCallForkRes()
}

type StopCallGatherRes interface {
	stopCallGatherRes()
}

type StopCallPlaybackRes interface {
	stopCallPlaybackRes()
}

type StopCallRecordingRes interface {
	stopCallRecordingRes()
}

type StopCallStreamingRes interface {
	stopCallStreamingRes()
}

type StopCallTranscriptionRes interface {
	stopCallTranscriptionRes()
}

type TransferCallRes interface {
	transferCallRes()
}

type UpdateClientStateRes interface {
	updateClientStateRes()
}

type UpdateTeXMLCallRecordingRes interface {
	updateTeXMLCallRecordingRes()
}

type UpdateTexmlApplicationRes interface {
	updateTexmlApplicationRes()
}

type UpdateTexmlConferenceParticipantRes interface {
	updateTexmlConferenceParticipantRes()
}

type UpdateTexmlConferenceRes interface {
	updateTexmlConferenceRes()
}

type UpdateVerifyProfileRes interface {
	updateVerifyProfileRes()
}

type VerifyVerificationCodeByPhoneNumberRes interface {
	verifyVerificationCodeByPhoneNumberRes()
}

type VerifyVerificationCodeRes interface {
	verifyVerificationCodeRes()
}
